---
kind: "operation"
client: "rug-cli 0.16.6"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/spring-boot-rest-service"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.3"
executor:
  name: "SetSpringBootParentVersionExecutor"
  group: "atomist-rugs"
  artifact: "spring-boot-editors"
  version: "0.5.2"
  origin:
    repo: "https://github.com/atomist-rugs/spring-boot-editors.git"
    branch: "2e4b222888ddbdee38a88d9d420119b859d0a508"
    sha: "2e4b222"
  parameters:
    - "spring_boot_version": "1.4.4.RELEASE"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "1979f9f98cad0eaf81eec3f512a80fdf3ae7d47f"
    sha: "1979f9f"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScriptGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "1979f9f98cad0eaf81eec3f512a80fdf3ae7d47f"
    sha: "1979f9f"
  parameters:
    - "generator_name": "NewSpringBootRestServiceProj"
    - "description": "create a new Spring Boot Rest Service project"
---
kind: "operation"
client: "rug-cli 0.27.0"
editor:
  name: "TestsToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.5.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-upgrade.git"
    branch: "7789ecdaccd329e70fde3bd77acf2215bc3ba5d2"
    sha: "7789ecd"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-editors"
  version: "0.27.1"
  origin:
    repo: "https://github.com/atomist/rug-editors.git"
    branch: "3de333b4aefd678ae14f196ab155647241de3746"
    sha: "3de333b"

---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"

