dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: FBJ1+ivAjik0kRVAzAWE+Py9fsPo0iElANMPpgcHabvHjGdJxiMwzOU74lYtGBKimWk7gLqfKTsfWD9O20XUpUVLjthcNIkTmBY/qrZYAn36bWCn7DIA6wV4yM1j1BhJvALxc4BYCQVZ9NSAC/41fSLHBfTneMs42jrfUC6TrnDmnK7HwJUY4/f89qbVlkc4bQqwmh9dm+g1cgL0NCQQ9nptYRtK2cZMChqBRuFq3zm7s8YJWwc3X7Obkx+mU3XpaigL0xC1wrFGCe9mD0P1X97+xZ9xIu1NzKvK2LII/YWmd6UKS/p2TkhZgJsDunxAKOJd4mTamhD0raSFM/Y1lCQh6TrHtHvKvmeygzyu5ZC+vPmirNIPJ6daHnxvy12XiOo7MTH7RBfEUCdH0PvJvoqg1eQefJcxq6WO3q43MvAxrm0m5+JF8MjL+K2/3izcoYSVDdE4ECtIo5NU/YMQZqS7otAOMJiH84wmpZ4lZ1UDnORm1jibUTqg71zg2MDLYTjwFGWOnVKrmMJ1FxaKFU72RBRkZRwr29YzmPD/NLxVzU6YYwV0kqHR0vYAsEEIAdSlm6S+YPxZs+8JT9W2Dy5IRh0b5Cgf3MirvE5J88bfXY8j+2lLtTNKdZu6wouOk9p5NMZDnxGeHDItwV7OpBTzZx1JP5YHAg8jQBmsesk=
  - secure: iHhl4aqh9T7RqyCGuERh4zUHKe6wwLxmGAIMlo8YTEXvyb9X9Tl4hQ+wjaDvlkSmEZKG9QXtIOVyDYBfexSbfnYhQkF9+a1Hs4CZQL1O7rbmoIMXZVD+51EcKXF1pwXSEaJ83BMiyC/B8OF/jt4zcxH4n1vnTVGTytHCSgN88ZULb02/PLJaBbsA4S7Z86iCLj9QXpZw9a+h866fEYz0Mv6qTCr20CckhkAHor+A/4REa7b32ZX4teXLII8pY9R61x+yHsjcD4loTn/G1qCcxjSetd4w+C1m/EsOOg7wE1GWy6NT5w8THCpnk8a2yz6ecOPRJ2E8LWLhl1UG3FusO5Yz6LgaGe8lauJsIJn13wCZXswhAbfCaZqqlG7tucUz8ipqRk0k/1rLlD0vQXSyhnNPfTRDmQBqv1Yf8/shLqHKJX1USZsKlv/Ro9dPKUHVwmPiK4pfq+d0ITgb4Zu9JpWkYRzBPiJQJo/9Lzi1u/CPhdBU1Kffv/psoADX/xTTMRpzbINCyw7sIs/NMIQAsYf3s7XhZzBuFj3bo0WUXpp3nEo0ppz0mIayEdRk/a7bRh0+MujBhb+avN9b/qx5KAjJmK9Tkp2+3fqkKkCurCgq6S8icN2Y1RZIAehl4m+OTQF+1SYPTvG4CiHbKPX3tpGDdIqgTM6pyogwFnVP0Ck=
  - secure: HihdS39P8yFITiDaA2laT8FgjEqdpQGiepWFwTzOAL/wNFuIynNzBsE0+LpN/ZvFnILv/B8kBfclZbILLyKqLGUiessWj+FHAq2HAf2TXeG2O+yrSk5elyjVWcxrdokRzQaRz91ZSFNzReu0XN1R04pP3dBUQaO2xn8DX7WuYdNCsrMD9r6JmLHJCr7jFDA7Rvva8tZNttG1Hx6FIf17oC8toCD1SlcNXHeuuMuTvnP6UrdIgqCEFylnN4LRSxh364PoX5pax1Hr+0Sj/cjaumhZ6zml5iEKKMOB6kxlTGR2Yx2Ce2IVARi5gyCfhwOvOVhCTiObUY7LURfZLFgsNLvL4PYhk2KZ6KNGQrk7EhNzyxb6EiEAoHK8T36MeqUhmc9bQUTDdQfCeXjI0/Tux90RVEgj/NMfiH5791zB+73iw3o0NmvXc+MWtnrgRsVN4lab35NWxKFkZhf1u09wPgtW0kpMS2cZdVNMHtuStjZ36uQlqCuPjrO9hot8I00nnoXQtvw7Ttgx7SR/44V6iu8KWIXiGbhFAJLf5+kKac/0LSwERQwMc+wTk56fXaDCP2AzgU007+L2RLngieh04gFsvFSAn9Him1W8yc32kTFE6krEwJSJ8bCTDAgy2exjnwYZbj6fWkpUVylIK+epcPXzLIwCqYtWuFdKxADNlgI=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
