language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: zkaum/Sfeqmw79AvG4GU/go/pCInSVYnQkcdqhK+l9EUSx9mRAnCfC1bcmi0pzPdFewV43LEP03zv2E22ZJY+rBLJZYZEphIfk1T7K0mvrbZqvSRcnkmRAylVUv9iFlMdutvGh+wGaFhc6P0m1pDF7zepFT7y14GwHxLG5Wt8zWmk+MwGdwvExsY3JyZB3Vfo8/dtA9Y3XpI2NHybE+Y5W2YWHeqzF2Ctg12aViLX8JA46dGBYwWDD8gB04YTE+iA6uqOjZPyqKlDtQYrZDKfq7LBjF4jX/6NzGjomeb2mn+NNAK4VCw/GANOylpRb760b0Gb17QxL/GZjYxiSm2YwI+RDLsOMqQnOSEjBgOLEmUh+O32SLOAAJqY5dHK6iCzJp2+LfjHIoBf0KYCP3NpfRkCI4ogC9y5SVHsCbBi/iZCKPzKAS/p3WJCnWbWROf68cuByh0+ubwsUb7ik2VoSMES1I5meoNgCYpnuLVWryD7AU36tXvokSgZclOET6ZsKWjlRfEhpgr6fZpJsZSGvzSZDLy8tPK+WvxvYSrvMJdxJqGN4438DH55aqm00yNpCEbGvR+sljSLa1M7CLd0A6NnG2RiBPGjRd8lZcQK+FOAi5WOD5clhfI1ZxYs9UIIQte1ZkkPvQQmfR3VXmpQJeSLsJ5UhcR6TquUORWZeY=
  - secure: LhiUm0jJfEMwYRZVhaiByQy1YWBQSrEKqxNzRguj7yHPV51KPGsOzwa0Rg92oy75eW9nK4NpaaTvwuj2AqxyqjDF+9xnhd3axrgIXhPpnoxnsl9ZpDoKAhHDTrcYArtv0lTJZdKu30IdWOHGVyWm1l3wtVHX6563+aGGCCHLJMDOzk3RriBP5hRpLgrJqSf5maCjuY0fsEFIXVima3PhfcfJW7DLW08tmbUrPjnfwVmqXSy83MIIkpN/ohOZXyvIWtPdcmo8xqWTUKaqtHyXwu4y3H5TMXUHfcwKdK0Xq15RM2n6+Wn8saW3qYC7w7eCkRe0tMK1WasHnuz1giGnpSFzr/0CJN7Snl9v0wE73IKxalILp5Kg1vvlrLVZvHKeDubi+ZguZl4hhwK8WwZMqt4/Zjh2Fbfx++QlqhGhboakNy9aW8ZwDLhLl/LriavnBN2zO2MDlKZLiIpt0jG41jX9ITKigQq4GOD42P4UNBWXx05RlxIKIiKDBySp9Os5FmVdCUoeRd7N3qy2wd5HD7OPtdMR+xQXA1vPwqvmhBPdObGhoCVlIJ7q9fbDvzNpPBC947KgMXAUIdT2LaJrTQsZAh7pax0Cr84aBzQh98ZuFwTNogCZvuK4kZfq/DZDYSyFaB6H4IS4SMWYmvNw+wa5SspoR+7ayHQ/hDgtH98=
  - secure: wyxKB3gdPRiVDqsG0KE+DkSesotNXiijdIhqnHMMR7IMX9mCgebfWQ78asvtZi1Fd+CNOgbelpPQxK0mGzagojksrXIHzE0p9PksRBnaxKsEjm+ebWfcedikaWN/WnJTJZqTX5w0eVDEQiGDI+uDYDXRqn/2Mv9YdEMDCpIcxrBX0uO16hAvJWggjrjdEiczuLTjeSGT7qZHmaxKAKoNPSX/craBp3qkOXVRuRh7e/cDJLkfFEn2dVLfQT5HIDpvDrj/SLRRcvsaPZ8DWYA/6B0x4JYVwdz2uAApQQTVNDqo9B5twYvCLU7S9xQUbIvKNfrUFQum4hLOGLU3JDho+ktr6dbB4loIfCs80COK0DzFJywVth1CLukBmceCF+G0vHBoZQ1bGqHwlnMga0pGTq1+y/rN3dZiLj+UagqGtJNPvM3H1L22Z72nHsPmbiyz10vxwwNkYhtwPtmlw8Wx2v6bjznzmrbCwAWcvmjuJaeyTfWgwra24tH+U85kLyO4UtW0bdV99KpVyxgxJQ5VIE13EKhHM0XlZOsArTHWCQthzUy2975Yyj9Y0H7z+0MrAcuiJqG34rgLXkgRA2EZ4YfxYB4FNj51uTCJjvtXbHoq+HApEeYxBigydZv87oAP1SFghU+4vfiXkAvuhJ9zVTlY7YwB92BOEenSpVPfe8Q=
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
